apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: demo-secret
data:
  MONGODB_URI:
   bW9uZ29kYjovL3Jvb3Q6cGFzc3dvcmRAbXktbW9uZ29kYi0wLm15LW1vbmdvZGItaGVhZGxlc3MuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNyxteS1tb25nb2RiLTEubXktbW9uZ29kYi1oZWFkbGVzcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3

