#Creates EBS type storage and defines it as a storage class f or kubernetes
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongodb-ebs-sc
provisioner: ebs.csi.aws.com  
parameters:
  type: gp3  # gp3 as its the current recommended for aws ebs
  fsType: ext4
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer 